let foods = {
    almond: {name: "Almond", group: "Nuts", mass: 1.5, price: 0.05, imgAvailable: true},
    anchovy: {name: "Anchovy", group: "Seafood", mass: 40, price: 2},
    apple: {name: "Apple", group: "Fruits", mass: 200, price: 0.5},
    asparagus: {name: "Asparagus", group: "Vegetables", mass: 20, price: 0.5},
    avocado: {name: "Avocado", group: "Fruits", mass: 150, price: 1},
    bacon: {name: "Bacon", group: "Meats", mass: 20, price: 1.5},
    banana: {name: "Banana", group: "Fruits", mass: 120, price: 1},
    basil: {name: "Basil Leaf", group: "Herbs / Spices", mass: 1, price: 0.1},
    bay: {name: "Bay Leaf", group: "Herbs / Spices", mass: 1, price: 0.1},
    beefChuck: {name: "Beef Chuck", group: "Meats", mass: 1000, price: 10},
    beetroot: {name: "Beetroot", group: "Vegetables", mass: 200, price: 1},
    blackberry: {name: "Blackberry", group: "Fruits", mass: 7, price: 0.05},
    blackPepper: {name: "Black Pepper", group: "Herbs / Spices", mass: 500, price: 3},
    blueberry: {name: "Blueberry", group: "Fruits", mass: 0.5, price: 0.05},
    bread: {name: "Bread", group: "Grains", mass: 400, cookSpeed: 10, price: 2.5},
    broccoli: {name: "Broccoli", group: "Vegetables", mass: 250, price: 1},
    brusselsSprouts: {name: "Brussels Sprouts", group: "Vegetables", mass: 10, price: 0.3},
    burgerBun: {name: "Burger Bun", group: "Grains", mass: 60, cookSpeed: 5, price: 0.8},
    burgerPatty: {name: "Burger Patty", group: "Meats", mass: 140, price: 4},
    buttonMushroom: {name: "Button Mushroom", group: "Vegetables", mass: 40, price: 0.5},
    cabbage: {name: "Cabbage", group: "Vegetables", mass: 750, price: 1.75},
    cantaloupe: {name: "Cantaloupe", group: "Fruits", mass: 1500, price: 2},
    carrot: {name: "Carrot", group: "Vegetables", mass: 65, price: 0.9},
    cashew: {name: "Cashew", group: "Nuts", mass: 1.5, price: 0.05},
    cheddar: {name: "Cheddar Cheese", group: "Cheeses", mass: 250, price: 2},
    cherry: {name: "Cherry", group: "Fruits", mass: 10, price: 0.05},
    chickenBreast: {name: "Chicken Breast", group: "Meats", mass: 175, price: 5},
    chickenLeg: {name: "Chicken Leg", group: "Meats", mass: 200, price: 5},
    chickenWing: {name: "Chicken Wing", group: "Meats", mass: 100, price: 5},
    chiliPepper: {name: "Chili Pepper", group: "Peppers", mass: 20, price: 1},
    chives: {name: "Chives", group: "Herbs / Spices", mass: 1, price: 0.1},
    cilantro: {name: "Cilantro Leaves", group: "Herbs / Spices", mass: 1, price: 0.1},
    cinnamonStick: {name: "Cinnamon Stick", group: "Herbs / Spices", mass: 2, price: 0.5},
    cocoa: {name: "Cocoa Bean", group: "Sweets", mass: 40, price: 0.25},
    coconut: {name: "Coconut", group: "Fruits", mass: 750, price: 1},
    cod: {name: "Cod", group: "Seafood", mass: 1000, price: 1},
    cornCob: {name: "Corn Cob", group: "Vegetables", mass: 20, price: 1},
    cucumber: {name: "Cucumber", group: "Vegetables", mass: 350, price: 1},
    dill: {name: "Dill", group: "Herbs / Spices", mass: 1, price: 0.1},
    duckBreast: {name: "Duck Breast", group: "Meats", mass: 400, price: 5},
    durian: {name: "Durian", group: "Fruits", mass: 2000, price: 4},
    egg: {name: "Egg", group: "Meats", mass: 60, price: 1.5},
    eggplant: {name: "Eggplant", group: "Fruits", mass: 550, price: 0.8},
    englishMuffin: {name: "English Muffin", group: "Grains", mass: 60, price: 1.2},
    feta: {name: "Feta Cheese", group: "Cheeses", mass: 250, price: 2},
    fig: {name: "Fig", group: "Fruits", mass: 40, price: 0.75},
    fusilli: {name: "Fusilli Noodles", group: "Pasta", mass: 1, price: 0.02},
    garlic: {name: "Garlic", group: "Herbs / Spices", mass: 5, price: 1.25},
    ginger: {name: "Ginger", group: "Herbs / Spices", mass: 200, price: 3},
    goatCheese: {name: "Goat Cheese", group: "Cheeses", mass: 250, price: 2},
    gorgonzola: {name: "Gorgonzola Cheese", group: "Cheeses", mass: 250, price: 2},
    grape: {name: "Grape", group: "Fruits", mass: 7, price: 0.05},
    greenBellPepper: {name: "Green Bell Pepper", group: "Peppers", mass: 150, price: 1},
    guava: {name: "Guava", group: "Fruits", mass: 55, price: 3.5},
    habanero: {name: "Habañero", group: "Peppers", mass: 55, price: 2},
    ham: {name: "Ham", group: "Meats", mass: 500, price: 6},
    honeydew: {name: "Honeydew", group: "Fruits", mass: 2500, price: 3},
    horseradish: {name: "Horseradish", group: "Herbs / Spices", mass: 2000, price: 6},
    jalapeno: {name: "Jalapeño", group: "Peppers", mass: 20, price: 2},
    lambChop: {name: "Lamb Chop", group: "Meats", mass: 100, price: 4},
    lasagna: {name: "Lasagna Noodles", group: "Pasta", mass: 10, price: 0.08},
    lemon: {name: "Lemon", group: "Fruits", mass: 70, price: 1},
    lettuce: {name: "Lettuce", group: "Vegetables", mass: 300, price: 1.5},
    lime: {name: "Lime", group: "Fruits", mass: 70, price: 1},
    lobster: {name: "Lobster", group: "Seafood", mass: 2000, price: 10},
    mango: {name: "Mango", group: "Fruits", mass: 200, price: 1},
    mint: {name: "Mint Leaf", group: "Herbs / Spices", mass: 1, price: 0.1},
    mozzarella: {name: "Mozzarella Cheese", group: "Cheeses", mass: 250, price: 2},
    onion: {name: "Onion", group: "Vegetables", mass: 120, price: 1.5},
    orange: {name: "Orange", group: "Fruits", mass: 150, price: 1},
    orangeBellPepper: {name: "Orange Bell Pepper", group: "Peppers", mass: 150, price: 1},
    oregano: {name: "Oregano", group: "Herbs / Spices", mass: 1, price: 0.1},
    oyster: {name: "Oyster", group: "Seafood", mass: 45, price: 8},
    pancetta: {name: "Pancetta", group: "Meats", mass: 350, price: 7.5},
    parmesan: {name: "Parmesan Cheese", group: "Cheeses", mass: 250, price: 2},
    parsley: {name: "Parsley Leaves", group: "Herbs / Spices", mass: 1, price: 0.1},
    parsleyRoot: {name: "Parsley Root", group: "Herbs / Spices", mass: 45, price: 1},
    parsnip: {name: "Parsnip", group: "Vegetables", mass: 115, price: 1},
    peach: {name: "Peach", group: "Fruits", mass: 150, price: 1},
    peanut: {name: "Peanut", group: "Nuts", mass: 0.8, price: 0.05},
    pear: {name: "Pear", group: "Fruits", mass: 180, price: 1},
    pecan: {name: "Pecan", group: "Nuts", mass: 1.8, price: 0.1},
    penne: {name: "Penne Noodles", group: "Pasta", mass: 1, price: 0.02},
    persimmon: {name: "Persimmon", group: "Fruits", mass: 170, price: 1},
    pineapple: {name: "Pineapple", group: "Fruits", mass: 1000, price: 4},
    porkSausage: {name: "Pork Sausage", group: "Meats", mass: 100, price: 6},
    porkChop: {name: "Pork Chop", group: "Meats", mass: 200, price: 4},
    porkShoulder: {name: "Pork Shoulder", group: "Meats", mass: 6500, price: 10},
    porkTenderloin: {name: "Pork Tenderloin", group: "Meats", mass: 2000, price: 8},
    potato: {name: "Potato", group: "Vegetables", mass: 200, price: 1},
    pumpkin: {name: "Pumpkin", group: "Vegetables", mass: 5000, price: 5},
    radish: {name: "Radish", group: "Vegetables", mass: 900, price: 1},
    rambutan: {name: "Rambutan", group: "Fruits", mass: 40, price: 1},
    raspberry: {name: "Raspberry", group: "Fruits", mass: 5, price: 0.05},
    redBellPepper: {name: "Red Bell Pepper", group: "Peppers", mass: 150, price: 1},
    redCabbage: {name: "Red Cabbage", group: "Vegetables", mass: 850, price: 3},
    redPepper: {name: "Red Pepper Flakes", group: "Herbs / Spices", mass: 500, price: 5},
    redPotato: {name: "Red Potato", group: "Vegetables", mass: 200, price: 1},
    rosemary: {name: "Rosemary", group: "Herbs / Spices", mass: 1, price: 0.1},
    sage: {name: "Sage Leaf", group: "Herbs / Spices", mass: 1, price: 0.1},
    salmon: {name: "Salmon Fillet", group: "Seafood", mass: 170, price: 5},
    salt: {name: "Salt", group: "Herbs / Spices", mass: 500, unavailable: true},
    saltCrystal: {name: "Salt Crystal", group: "Herbs / Spices", mass: 500, price: 5, grind: {id: "salt", mass: 500}},
    sausage: {name: "Sausage", group: "Meats", mass: 100, price: 4},
    scallion: {name: "Scallion", group: "Vegetables", mass: 15, price: 1.25},
    scallop: {name: "Scallop", group: "Seafood", mass: 15, price: 3},
    serrano: {name: "Serrano Pepper", group: "Peppers", mass: 10, price: 3},
    shrimp: {name: "Shrimp", group: "Seafood", mass: 2, price: 1},
    spaghetti: {name: "Spaghetti Noodles", group: "Pasta", mass: 1, price: 0.03},
    starAnise: {name: "Star Anise", group: "Herbs / Spices", mass: 30, price: 4},
    steak: {name: "Steak", group: "Meats", mass: 225, price: 5},
    strawberry: {name: "Strawberry", group: "Fruits", mass: 12, price: 0.1},
    swordfish: {name: "Swordfish", group: "Seafood", mass: 3000, price: 30},
    tBoneSteak: {name: "T-Bone Steak", group: "Meats", mass: 425, price: 10},
    thyme: {name: "Thyme", group: "Herbs / Spices", mass: 1, price: 0.1},
    tomato: {name: "Tomato", group: "Fruits", mass: 170, price: 1},
    tortellini: {name: "Tortellini", group: "Pasta", mass: 5, price: 0.05},
    tortilla: {name: "Tortilla", group: "Grains", mass: 45, price: 0.75},
    trout: {name: "Trout", group: "Seafood", mass: 500, price: 5},
    tuna: {name: "Tuna", group: "Seafood", mass: 500, price: 4},
    walnut: {name: "Walnut", group: "Nuts", mass: 11, price: 0.05},
    watermelon: {name: "Watermelon", group: "Fruits", mass: 3000, price: 8},
    yakCheese: {name: "Yak Cheese", group: "Cheeses", mass: 250, price: 3},
    yellowBellPepper: {name: "Yellow Bell Pepper", group: "Peppers", mass: 150, price: 1},
    ziti: {name: "Ziti", group: "Pasta", mass: 2, price: 0.03},
    zucchini: {name: "Zucchini", group: "Vegetables", mass: 200, price: 1},

    almondMilk: {name: "Almond Milk", group: "Liquids", volume: 500, price: 5},
    avocadoOil: {name: "Avocado Oil", group: "Oils", volume: 1000, price: 3},
    balsamicVinegar: {name: "Balsamic Vinegar", group: "Liquids", volume: 1000, price: 5},
    barbecueSauce: {name: "Barbecue Sauce", group: "Condiments", volume: 500, price: 5},
    bavarianBeerVinegar: {name: "Bavarian Beer Vinegar", group: "Liquids", volume: 1000, price: 5},
    chickenBroth: {name: "Chicken Broth", group: "Liquids", volume: 1000, price: 7},
    clarifiedButter: {name: "Clarified Butter", group: "Liquids", volume: 1000, price: 6},
    coconutMilk: {name: "Coconut Milk", group: "Liquids", volume: 500, price: 5},
    cola: {name: "Cola", group: "Liquids", volume: 500, price: 3},
    dijonMustard: {name: "Dijon Mustard", group: "Condiments", volume: 500, price: 6},
    dusseldorfMustard: {name: "Düsseldorf Mustard", group: "Condiments", volume: 500, price: 6},
    elderflowerJelly: {name: "Elderflower Jelly", group: "Liquids", volume: 500, price: 8},
    hoisinSauce: {name: "Hoisin Sauce", group: "Liquids", volume: 1000, price: 5},
    honey: {name: "Honey", group: "Liquids", volume: 1000, price: 6},
    ketchup: {name: "Ketchup", group: "Condiments", volume: 500, price: 5},
    lemonJuice: {name: "Lemon Juice", group: "Liquids", volume: 1000, price: 9},
    limeJuice: {name: "Lime Juice", group: "Liquids", volume: 1000, price: 9},
    milk: {name: "Milk", group: "Liquids", volume: 500, price: 5},
    mustard: {name: "Mustard", group: "Condiments", volume: 500, price: 5},
    oliveOil: {name: "Olive Oil", group: "Oils", volume: 1000, price: 3},
    peanutOil: {name: "Peanut Oil", group: "Oils", volume: 1000, price: 3},
    pesto: {name: "Pesto", group: "Liquids", volume: 500, price: 6},
    redWine: {name: "Red Wine", group: "Liquids", volume: 1000, price: 8},
    redcurrantJelly: {name: "Redcurrant Jelly", group: "Liquids", volume: 500, price: 8},
    riceVinegar: {name: "Rice Vinegar", group: "Liquids", volume: 1000, price: 5},
    riceWine: {name: "Rice Wine", group: "Liquids", volume: 1000, price: 8},
    salsa: {name: "Salsa", group: "Liquids", volume: 500, price: 5},
    sesameOil: {name: "Sesame Oil", group: "Oils", volume: 1000, price: 3},
    sourCream: {name: "Sour Cream", group: "Liquids", volume: 500, price: 4},
    soySauce: {name: "Soy Sauce", group: "Liquids", volume: 1000, price: 5},
    sunflowerOil: {name: "Sunflower Oil", group: "Oils", volume: 1000, price: 3},
    vanillaExtract: {name: "Vanilla Extract", group: "Oils", volume: 1000, price: 4},
    water: {name: "Water", group: "Liquids", volume: 1000, price: 0},
    whiteVinegar: {name: "White Vinegar", group: "Liquids", volume: 1000, price: 5},
    whiteWine: {name: "White Wine", group: "Liquids", volume: 1000, price: 8},
    wineVinegar: {name: "Wine Vinegar", group: "Liquids", volume: 1000, price: 5},

    penny: {name: "Penny", group: "Money", mass: 2.5, price: 0.01},
    nickel: {name: "Nickel", group: "Money", mass: 5, price: 0.05},
    dime: {name: "Dime", group: "Money", mass: 2.268, price: 0.1},
    quarter: {name: "Quarter", group: "Money", mass: 5.67, price: 0.25},
    fiftyCents: {name: "50 Cent Coin", group: "Money", mass: 7.8, price: 0.5},
    one: {name: "$1 Bill", group: "Money", mass: 1, price: 1},
    two: {name: "$2 Bill", group: "Money", mass: 1, price: 2},
    five: {name: "$5 Bill", group: "Money", mass: 1, price: 5},
    ten: {name: "$10 Bill", group: "Money", mass: 1, price: 10},
    twenty: {name: "$20 Bill", group: "Money", mass: 1, price: 20},
    fifty: {name: "$50 Bill", group: "Money", mass: 1, price: 50},
    hundred: {name: "$100 Bill", group: "Money", mass: 1, price: 100},
    fiveHundred: {name: "$500 Bill", group: "Money", mass: 1, price: 500},
    thousand: {name: "$1,000 Bill", group: "Money", mass: 1, price: 1000},
    tenThousand: {name: "$10,000 Bill", group: "Money", mass: 1, price: 10000},
    hundredThousand: {name: "$100,000 Bill", group: "Money", mass: 1, price: 100000},
    million: {name: "$1 Million Bill", group: "Money", mass: 1, price: 1e6},
    tenMillion: {name: "$10 Million Bill", group: "Money", mass: 1, price: 1e7},
    hundredMillion: {name: "$100 Million Bill", group: "Money", mass: 1, price: 1e8},
    billion: {name: "$1 Billion Bill", group: "Money", mass: 1, price: 1e9}
};

const animations = {
    autoCutter: {
        img: [
            "img/autoCutter/0.png",
            "img/autoCutter/1.png",
            "img/autoCutter/2.png",
            "img/autoCutter/3.png",
            "img/autoCutter/4.png",
            "img/autoCutter/5.png",
            "img/autoCutter/6.png",
            "img/autoCutter/7.png"
        ],
        fps: 50
    }
};