let foods = {
    almond: {name: "Almond", group: "Nuts", mass: 1.5, price: 0.05, imgAvailable: true},
    anchovy: {name: "Anchovy", group: "Seafood", mass: 40, price: 2},
    apple: {name: "Apple", group: "Fruits", mass: 200, price: 1},
    asparagus: {name: "Asparagus", group: "Vegetables", mass: 20, price: 0.5},
    avocado: {name: "Avocado", group: "Fruits", mass: 150, price: 1},
    bacon: {name: "Bacon", group: "Meats", mass: 20, price: 1.5},
    banana: {name: "Banana", group: "Fruits", mass: 120, price: 1},
    basil: {name: "Basil Leaf", group: "Herbs / Spices", mass: 1, price: 0.1},
    bay: {name: "Bay Leaf", group: "Herbs / Spices", mass: 1, price: 0.1},
    beefChuck: {name: "Beef Chuck", group: "Meats", mass: 1000, price: 10},
    beetroot: {name: "Beetroot", group: "Vegetables", mass: 200, price: 1},
    blackberry: {name: "Blackberry", group: "Fruits", mass: 7, price: 0.05},
    blackPepper: {name: "Black Pepper", group: "Herbs / Spices", mass: 500, price: 3},
    blueberry: {name: "Blueberry", group: "Fruits", mass: 0.5, price: 0.05},
    bread: {name: "Bread", group: "Grains", mass: 400, cookSpeed: 10, price: 2.5},
    broccoli: {name: "Broccoli", group: "Vegetables", mass: 250, price: 1},
    brusselsSprouts: {name: "Brussels Sprouts", group: "Vegetables", mass: 10, price: 0.3},
    burgerBun: {name: "Burger Bun", group: "Grains", mass: 60, cookSpeed: 5, price: 0.8},
    burgerPatty: {name: "Burger Patty", group: "Meats", mass: 140, price: 4},
    buttonMushroom: {name: "Button Mushroom", group: "Vegetables", mass: 40, price: 0.5},
    cabbage: {name: "Cabbage", group: "Vegetables", mass: 750, price: 1.75},
    cantaloupe: {name: "Cantaloupe", group: "Fruits", mass: 1500, price: 2},
    carrot: {name: "Carrot", group: "Vegetables", mass: 65, price: 0.9},
    cashew: {name: "Cashew", group: "Nuts", mass: 1.5, price: 0.05},
    cheddar: {name: "Cheddar Cheese", group: "Cheeses", mass: 250, price: 2},
    cherry: {name: "Cherry", group: "Fruits", mass: 10, price: 0.05},
    chickenBreast: {name: "Chicken Breast", group: "Meats", mass: 175, price: 5},
    chickenLeg: {name: "Chicken Leg", group: "Meats", mass: 200, price: 5},
    chickenWing: {name: "Chicken Wing", group: "Meats", mass: 100, price: 5},
    chiliPepper: {name: "Chili Pepper", group: "Peppers", mass: 20, price: 1},
    chives: {name: "Chives", group: "Herbs / Spices", mass: 1, price: 0.1},
    cilantro: {name: "Cilantro Leaves", group: "Herbs / Spices", mass: 1, price: 0.1},
    cinnamonStick: {name: "Cinnamon Stick", group: "Herbs / Spices", mass: 2, price: 0.5},
    cocoa: {name: "Cocoa Bean", group: "Sweets", mass: 40, price: 0.25},
    coconut: {name: "Coconut", group: "Fruits", mass: 750, price: 1},
    cod: {name: "Cod", group: "Seafood", mass: 1000, price: 1},
    cornCob: {name: "Corn Cob", group: "Vegetables", mass: 20, price: 1},
    cucumber: {name: "Cucumber", group: "Vegetables", mass: 350, price: 1},
    dill: {name: "Dill", group: "Herbs / Spices", mass: 1, price: 0.1},
    duckBreast: {name: "Duck Breast", group: "Meats", mass: 400, price: 5},
    durian: {name: "Durian", group: "Fruits", mass: 2000, price: 4},
    egg: {name: "Egg", group: "Meats", mass: 60, price: 1.5},
    eggplant: {name: "Eggplant", group: "Fruits", mass: 550, price: 0.8},
    englishMuffin: {name: "English Muffin", group: "Grains", mass: 60, price: 1.2},
    feta: {name: "Feta Cheese", group: "Cheeses", mass: 250, price: 2},
    fig: {name: "Fig", group: "Fruits", mass: 40, price: 0.75},
    fusilli: {name: "Fusilli Noodles", group: "Pasta", mass: 1, price: 0.02},
    garlic: {name: "Garlic", group: "Herbs / Spices", mass: 5, price: 1.25},
    ginger: {name: "Ginger", group: "Herbs / Spices", mass: 200, price: 3},
    goatCheese: {name: "Goat Cheese", group: "Cheeses", mass: 250, price: 2},
    gorgonzola: {name: "Gorgonzola Cheese", group: "Cheeses", mass: 250, price: 2},
    grape: {name: "Grape", group: "Fruits", mass: 7, price: 0.05},
    greenBellPepper: {name: "Green Bell Pepper", group: "Peppers", mass: 150, price: 1},
    guava: {name: "Guava", group: "Fruits", mass: 55, price: 3.5},
    habanero: {name: "Habañero", group: "Peppers", mass: 55, price: 2},
    ham: {name: "Ham", group: "Meats", mass: 500, price: 6},
    honeydew: {name: "Honeydew", group: "Fruits", mass: 2500, price: 3},
    horseradish: {name: "Horseradish", group: "Herbs / Spices", mass: 2000, price: 6},
    jalapeno: {name: "Jalapeño", group: "Peppers", mass: 20, price: 2},
    lambChop: {name: "Lamb Chop", group: "Meats", mass: 100, price: 4},
    lasagna: {name: "Lasagna Noodles", group: "Pasta", mass: 10, price: 0.08},
    lemon: {name: "Lemon", group: "Fruits", mass: 70, price: 1},
    lettuce: {name: "Lettuce", group: "Vegetables", mass: 300, price: 1.5},
    lime: {name: "Lime", group: "Fruits", mass: 70, price: 1},
    lobster: {name: "Lobster", group: "Seafood", mass: 2000, price: 10},
    mango: {name: "Mango", group: "Fruits", mass: 200, price: 1},
    mint: {name: "Mint Leaf", group: "Herbs / Spices", mass: 1, price: 0.1},
    mozzarella: {name: "Mozzarella Cheese", group: "Cheeses", mass: 250, price: 2},
    onion: {name: "Onion", group: "Vegetables", mass: 120, price: 1.5},
    orange: {name: "Orange", group: "Fruits", mass: 150, price: 1},
    orangeBellPepper: {name: "Orange Bell Pepper", group: "Peppers", mass: 150, price: 1},
    oregano: {name: "Oregano", group: "Herbs / Spices", mass: 1, price: 0.1},
    oyster: {name: "Oyster", group: "Seafood", mass: 45, price: 8},
    pancetta: {name: "Pancetta", group: "Meats", mass: 350, price: 7.5},
    parmesan: {name: "Parmesan Cheese", group: "Cheeses", mass: 250, price: 2},
    parsley: {name: "Parsley Leaves", group: "Herbs / Spices", mass: 1, price: 0.1},
    parsleyRoot: {name: "Parsley Root", group: "Herbs / Spices", mass: 45, price: 1},
    parsnip: {name: "Parsnip", group: "Vegetables", mass: 115, price: 1},
    peach: {name: "Peach", group: "Fruits", mass: 150, price: 1},
    peanut: {name: "Peanut", group: "Nuts", mass: 0.8, price: 0.05},
    pear: {name: "Pear", group: "Fruits", mass: 180, price: 1},
    pecan: {name: "Pecan", group: "Nuts", mass: 1.8, price: 0.1},
    penne: {name: "Penne Noodles", group: "Pasta", mass: 1, price: 0.02},
    persimmon: {name: "Persimmon", group: "Fruits", mass: 170, price: 1},
    pineapple: {name: "Pineapple", group: "Fruits", mass: 1000, price: 4},
    porkSausage: {name: "Pork Sausage", group: "Meats", mass: 100, price: 6},
    porkChop: {name: "Pork Chop", group: "Meats", mass: 200, price: 4},
    porkShoulder: {name: "Pork Shoulder", group: "Meats", mass: 6500, price: 10},
    porkTenderloin: {name: "Pork Tenderloin", group: "Meats", mass: 2000, price: 8},
    potato: {name: "Potato", group: "Vegetables", mass: 200, price: 1},
    pumpkin: {name: "Pumpkin", group: "Vegetables", mass: 5000, price: 5},
    radish: {name: "Radish", group: "Vegetables", mass: 900, price: 1},
    rambutan: {name: "Rambutan", group: "Fruits", mass: 40, price: 1},
    raspberry: {name: "Raspberry", group: "Fruits", mass: 5, price: 0.05},
    redBellPepper: {name: "Red Bell Pepper", group: "Peppers", mass: 150, price: 1},
    redCabbage: {name: "Red Cabbage", group: "Vegetables", mass: 850, price: 3},
    redPepper: {name: "Red Pepper Flakes", group: "Herbs / Spices", mass: 500, price: 5},
    redPotato: {name: "Red Potato", group: "Vegetables", mass: 200, price: 1},
    rosemary: {name: "Rosemary", group: "Herbs / Spices", mass: 1, price: 0.1},
    sage: {name: "Sage Leaf", group: "Herbs / Spices", mass: 1, price: 0.1},
    salmon: {name: "Salmon Fillet", group: "Seafood", mass: 170, price: 5},
    salt: {name: "Salt", group: "Herbs / Spices", mass: 500, unavailable: true},
    saltCrystal: {name: "Salt Crystal", group: "Herbs / Spices", mass: 500, price: 5, grind: {id: "salt", mass: 500}},
    sausage: {name: "Sausage", group: "Meats", mass: 100, price: 4},
    scallion: {name: "Scallion", group: "Vegetables", mass: 15, price: 1.25},
    scallop: {name: "Scallop", group: "Seafood", mass: 15, price: 3},
    serrano: {name: "Serrano Pepper", group: "Peppers", mass: 10, price: 3},
    shrimp: {name: "Shrimp", group: "Seafood", mass: 2, price: 1},
    spaghetti: {name: "Spaghetti Noodles", group: "Pasta", mass: 1, price: 0.03},
    starAnise: {name: "Star Anise", group: "Herbs / Spices", mass: 30, price: 4},
    steak: {name: "Steak", group: "Meats", mass: 225, price: 5},
    strawberry: {name: "Strawberry", group: "Fruits", mass: 12, price: 0.1},
    swordfish: {name: "Swordfish", group: "Seafood", mass: 3000, price: 30},
    tBoneSteak: {name: "T-Bone Steak", group: "Meats", mass: 425, price: 10},
    thyme: {name: "Thyme", group: "Herbs / Spices", mass: 1, price: 0.1},
    tomato: {name: "Tomato", group: "Fruits", mass: 170, price: 1},
    tortellini: {name: "Tortellini", group: "Pasta", mass: 5, price: 0.05},
    tortilla: {name: "Tortilla", group: "Grains", mass: 45, price: 0.75},
    trout: {name: "Trout", group: "Seafood", mass: 500, price: 5},
    tuna: {name: "Tuna", group: "Seafood", mass: 500, price: 4},
    walnut: {name: "Walnut", group: "Nuts", mass: 11, price: 0.05},
    watermelon: {name: "Watermelon", group: "Fruits", mass: 3000, price: 8},
    yakCheese: {name: "Yak Cheese", group: "Cheeses", mass: 250, price: 3},
    yellowBellPepper: {name: "Yellow Bell Pepper", group: "Peppers", mass: 150, price: 1},
    ziti: {name: "Ziti", group: "Pasta", mass: 2, price: 0.03},
    zucchini: {name: "Zucchini", group: "Vegetables", mass: 200, price: 1},

    almondMilk: {name: "Almond Milk", group: "Liquids", volume: 500, price: 5},
    avocadoOil: {name: "Avocado Oil", group: "Oils", volume: 1000, price: 3},
    balsamicVinegar: {name: "Balsamic Vinegar", group: "Liquids", volume: 1000, price: 5},
    barbecueSauce: {name: "Barbecue Sauce", group: "Condiments", volume: 500, price: 5},
    bavarianBeerVinegar: {name: "Bavarian Beer Vinegar", group: "Liquids", volume: 1000, price: 5},
    chickenBroth: {name: "Chicken Broth", group: "Liquids", volume: 1000, price: 7},
    clarifiedButter: {name: "Clarified Butter", group: "Liquids", volume: 1000, price: 6},
    coconutMilk: {name: "Coconut Milk", group: "Liquids", volume: 500, price: 5},
    cola: {name: "Cola", group: "Liquids", volume: 500, price: 3},
    dijonMustard: {name: "Dijon Mustard", group: "Condiments", volume: 500, price: 6},
    dusseldorfMustard: {name: "Düsseldorf Mustard", group: "Condiments", volume: 500, price: 6},
    elderflowerJelly: {name: "Elderflower Jelly", group: "Liquids", volume: 500, price: 8},
    hoisinSauce: {name: "Hoisin Sauce", group: "Liquids", volume: 1000, price: 5},
    honey: {name: "Honey", group: "Liquids", volume: 1000, price: 6},
    ketchup: {name: "Ketchup", group: "Condiments", volume: 500, price: 5},
    lemonJuice: {name: "Lemon Juice", group: "Liquids", volume: 1000, price: 9},
    limeJuice: {name: "Lime Juice", group: "Liquids", volume: 1000, price: 9},
    milk: {name: "Milk", group: "Liquids", volume: 500, price: 5},
    mustard: {name: "Mustard", group: "Condiments", volume: 500, price: 5},
    oliveOil: {name: "Olive Oil", group: "Oils", volume: 1000, price: 3},
    peanutOil: {name: "Peanut Oil", group: "Oils", volume: 1000, price: 3},
    pesto: {name: "Pesto", group: "Liquids", volume: 500, price: 6},
    redWine: {name: "Red Wine", group: "Liquids", volume: 1000, price: 8},
    redcurrantJelly: {name: "Redcurrant Jelly", group: "Liquids", volume: 500, price: 8},
    riceVinegar: {name: "Rice Vinegar", group: "Liquids", volume: 1000, price: 5},
    riceWine: {name: "Rice Wine", group: "Liquids", volume: 1000, price: 8},
    salsa: {name: "Salsa", group: "Liquids", volume: 500, price: 5},
    sesameOil: {name: "Sesame Oil", group: "Oils", volume: 1000, price: 3},
    sourCream: {name: "Sour Cream", group: "Liquids", volume: 500, price: 4},
    soySauce: {name: "Soy Sauce", group: "Liquids", volume: 1000, price: 5},
    sunflowerOil: {name: "Sunflower Oil", group: "Oils", volume: 1000, price: 3},
    vanillaExtract: {name: "Vanilla Extract", group: "Oils", volume: 1000, price: 4},
    water: {name: "Water", group: "Liquids", volume: 1000, price: 0},
    whiteVinegar: {name: "White Vinegar", group: "Liquids", volume: 1000, price: 5},
    whiteWine: {name: "White Wine", group: "Liquids", volume: 1000, price: 8},
    wineVinegar: {name: "Wine Vinegar", group: "Liquids", volume: 1000, price: 5},

    penny: {name: "Penny", group: "Money", mass: 1, price: 0.01},
    nickel: {name: "Nickel", group: "Money", mass: 1, price: 0.05},
    dime: {name: "Dime", group: "Money", mass: 1, price: 0.1},
    quarter: {name: "Quarter", group: "Money", mass: 1, price: 0.25},
    fiftyCents: {name: "Half-Dollar", group: "Money", mass: 1, price: 0.5},
    one: {name: "$1 Bill", group: "Money", mass: 1, price: 1},
    two: {name: "$2 Bill", group: "Money", mass: 1, price: 2},
    five: {name: "$5 Bill", group: "Money", mass: 1, price: 5},
    ten: {name: "$10 Bill", group: "Money", mass: 1, price: 10},
    twenty: {name: "$20 Bill", group: "Money", mass: 1, price: 20},
    fifty: {name: "$50 Bill", group: "Money", mass: 1, price: 50},
    hundred: {name: "$100 Bill", group: "Money", mass: 1, price: 100},
    fiveHundred: {name: "$500 Bill", group: "Money", mass: 1, price: 500},
    thousand: {name: "$1,000 Bill", group: "Money", mass: 1, price: 1000},
    tenThousand: {name: "$10,000 Bill", group: "Money", mass: 1, price: 10000},
    hundredThousand: {name: "$100,000 Bill", group: "Money", mass: 1, price: 100000},
    million: {name: "$1 Million Bill", group: "Money", mass: 1, price: 1e6},
    tenMillion: {name: "$10 Million Bill", group: "Money", mass: 1, price: 1e7},
    hundredMillion: {name: "$100 Million Bill", group: "Money", mass: 1, price: 1e8},
    billion: {name: "$1 Billion Bill", group: "Money", mass: 1, price: 1e9},
    tenBillion: {name: "$10 Billion Bill", group: "Money", mass: 1, price: 1e10},
    hundredBillion: {name: "$100 Billion Bill", group: "Money", mass: 1, price: 1e11},
    trillion: {name: "$1 Trillion Bill", group: "Money", mass: 1, price: 1e12},
    tenTrillion: {name: "$10 Trillion Bill", group: "Money", mass: 1, price: 1e13},
    hundredTrillion: {name: "$100 Trillion Bill", group: "Money", mass: 1, price: 1e14},
    quadrillion: {name: "$1 Quadrillion Bill", group: "Money", mass: 1, price: 1e15},
    tenQuadrillion: {name: "$10 Quadrillion Bill", group: "Money", mass: 1, price: 1e16},
    hundredQuadrillion: {name: "$100 Quadrillion Bill", group: "Money", mass: 1, price: 1e17},
    quintillion: {name: "$1 Quintillion Bill", group: "Money", mass: 1, price: 1e18},
    tenQuintillion: {name: "$10 Quintillion Bill", group: "Money", mass: 1, price: 1e19},
    hundredQuintillion: {name: "$100 Quintillion Bill", group: "Money", mass: 1, price: 1e20},
    sextillion: {name: "$1 Sextillion Bill", group: "Money", mass: 1, price: 1e21},
    tenSextillion: {name: "$10 Sextillion Bill", group: "Money", mass: 1, price: 1e22},
    hundredSextillion: {name: "$100 Sextillion Bill", group: "Money", mass: 1, price: 1e23},
    septillion: {name: "$1 Septillion Bill", group: "Money", mass: 1, price: 1e24},
    tenSeptillion: {name: "$10 Septillion Bill", group: "Money", mass: 1, price: 1e25},
    hundredSeptillion: {name: "$100 Septillion Bill", group: "Money", mass: 1, price: 1e26},
    octillion: {name: "$1 Octillion Bill", group: "Money", mass: 1, price: 1e27},
    tenOctillion: {name: "$10 Octillion Bill", group: "Money", mass: 1, price: 1e28},
    hundredOctillion: {name: "$100 Octillion Bill", group: "Money", mass: 1, price: 1e29},
    nonillion: {name: "$1 Nonillion Bill", group: "Money", mass: 1, price: 1e30},
    tenNonillion: {name: "$10 Nonillion Bill", group: "Money", mass: 1, price: 1e31},
    hundredNonillion: {name: "$100 Nonillion Bill", group: "Money", mass: 1, price: 1e32},
    decillion: {name: "$1 Decillion Bill", group: "Money", mass: 1, price: 1e33},
    e34: {name: "$10 Decillion Bill", group: "Money", mass: 1, price: 1e34},
    e35: {name: "$100 Decillion Bill", group: "Money", mass: 1, price: 1e35},
    e36: {name: "$1 Undecillion Bill", group: "Money", mass: 1, price: 1e36},
    e37: {name: "$10 Undecillion Bill", group: "Money", mass: 1, price: 1e37},
    e38: {name: "$100 Undecillion Bill", group: "Money", mass: 1, price: 1e38},
    e39: {name: "$1 Duodecillion Bill", group: "Money", mass: 1, price: 1e39},
    e40: {name: "$10 Duodecillion Bill", group: "Money", mass: 1, price: 1e40},
    e41: {name: "$100 Duodecillion Bill", group: "Money", mass: 1, price: 1e41},
    e42: {name: "$1 Tredecillion Bill", group: "Money", mass: 1, price: 1e42},
    e43: {name: "$10 Tredecillion Bill", group: "Money", mass: 1, price: 1e43},
    e44: {name: "$100 Tredecillion Bill", group: "Money", mass: 1, price: 1e44},
    e45: {name: "$1 Quattuordecillion Bill", group: "Money", mass: 1, price: 1e45},
    e46: {name: "$10 Quattuordecillion Bill", group: "Money", mass: 1, price: 1e46},
    e47: {name: "$100 Quattuordecillion Bill", group: "Money", mass: 1, price: 1e47},
    e48: {name: "$1 Quindecillion Bill", group: "Money", mass: 1, price: 1e48},
    e49: {name: "$10 Quindecillion Bill", group: "Money", mass: 1, price: 1e49},
    e50: {name: "$100 Quindecillion Bill", group: "Money", mass: 1, price: 1e50},
    e51: {name: "$1 Sexdecillion Bill", group: "Money", mass: 1, price: 1e51},
    e52: {name: "$10 Sexdecillion Bill", group: "Money", mass: 1, price: 1e52},
    e53: {name: "$100 Sexdecillion Bill", group: "Money", mass: 1, price: 1e53},
    e54: {name: "$1 Septendecillion Bill", group: "Money", mass: 1, price: 1e54},
    e55: {name: "$10 Septendecillion Bill", group: "Money", mass: 1, price: 1e55},
    e56: {name: "$100 Septendecillion Bill", group: "Money", mass: 1, price: 1e56},
    e57: {name: "$1 Octodecillion Bill", group: "Money", mass: 1, price: 1e57},
    e58: {name: "$10 Octodecillion Bill", group: "Money", mass: 1, price: 1e58},
    e59: {name: "$100 Octodecillion Bill", group: "Money", mass: 1, price: 1e59},
    e60: {name: "$1 Novemdecillion Bill", group: "Money", mass: 1, price: 1e60},
    e61: {name: "$10 Novemdecillion Bill", group: "Money", mass: 1, price: 1e61},
    e62: {name: "$100 Novemdecillion Bill", group: "Money", mass: 1, price: 1e62},
    e63: {name: "$1 Vigintillion Bill", group: "Money", mass: 1, price: 1e63},
    e64: {name: "$10 Vigintillion Bill", group: "Money", mass: 1, price: 1e64},
    e65: {name: "$100 Vigintillion Bill", group: "Money", mass: 1, price: 1e65},
    e66: {name: "$1 Unvigintillion Bill", group: "Money", mass: 1, price: 1e66},
    e67: {name: "$10 Unvigintillion Bill", group: "Money", mass: 1, price: 1e67},
    e68: {name: "$100 Unvigintillion Bill", group: "Money", mass: 1, price: 1e68},
    e69: {name: "$1 Duovigintillion Bill", group: "Money", mass: 1, price: 1e69},
    e70: {name: "$10 Duovigintillion Bill", group: "Money", mass: 1, price: 1e70},
    e71: {name: "$100 Duovigintillion Bill", group: "Money", mass: 1, price: 1e71},
    e72: {name: "$1 Trevigintillion Bill", group: "Money", mass: 1, price: 1e72},
    e73: {name: "$10 Trevigintillion Bill", group: "Money", mass: 1, price: 1e73},
    e74: {name: "$100 Trevigintillion Bill", group: "Money", mass: 1, price: 1e74},
    e75: {name: "$1 Quattuorvigintillion Bill", group: "Money", mass: 1, price: 1e75},
    e76: {name: "$10 Quattuorvigintillion Bill", group: "Money", mass: 1, price: 1e76},
    e77: {name: "$100 Quattuorvigintillion Bill", group: "Money", mass: 1, price: 1e77},
    e78: {name: "$1 Quinvigintillion Bill", group: "Money", mass: 1, price: 1e78},
    e79: {name: "$10 Quinvigintillion Bill", group: "Money", mass: 1, price: 1e79},
    e80: {name: "$100 Quinvigintillion Bill", group: "Money", mass: 1, price: 1e80},
    e81: {name: "$1 Sexvigintillion Bill", group: "Money", mass: 1, price: 1e81},
    e82: {name: "$10 Sexvigintillion Bill", group: "Money", mass: 1, price: 1e82},
    e83: {name: "$100 Sexvigintillion Bill", group: "Money", mass: 1, price: 1e83},
    e84: {name: "$1 Septenvigintillion Bill", group: "Money", mass: 1, price: 1e84},
    e85: {name: "$10 Septenvigintillion Bill", group: "Money", mass: 1, price: 1e85},
    e86: {name: "$100 Septenvigintillion Bill", group: "Money", mass: 1, price: 1e86},
    e87: {name: "$1 Octovigintillion Bill", group: "Money", mass: 1, price: 1e87},
    e88: {name: "$10 Octovigintillion Bill", group: "Money", mass: 1, price: 1e88},
    e89: {name: "$100 Octovigintillion Bill", group: "Money", mass: 1, price: 1e89},
    e90: {name: "$1 Novemvigintillion Bill", group: "Money", mass: 1, price: 1e90},
    e91: {name: "$10 Novemvigintillion Bill", group: "Money", mass: 1, price: 1e91},
    e92: {name: "$100 Novemvigintillion Bill", group: "Money", mass: 1, price: 1e92},
    e93: {name: "$1 Trigintillion Bill", group: "Money", mass: 1, price: 1e93},
    e94: {name: "$10 Trigintillion Bill", group: "Money", mass: 1, price: 1e94},
    e95: {name: "$100 Trigintillion Bill", group: "Money", mass: 1, price: 1e95},
    e96: {name: "$1 Untrigintillion Bill", group: "Money", mass: 1, price: 1e96},
    e97: {name: "$10 Untrigintillion Bill", group: "Money", mass: 1, price: 1e97},
    e98: {name: "$100 Untrigintillion Bill", group: "Money", mass: 1, price: 1e98},
    e99: {name: "$1 Duotrigintillion Bill", group: "Money", mass: 1, price: 1e99},
    e100: {name: "$10 Duotrigintillion Bill", group: "Money", mass: 1, price: 1e100},
    e101: {name: "$100 Duotrigintillion Bill", group: "Money", mass: 1, price: 1e101},
    e102: {name: "$1 Tretrigintillion Bill", group: "Money", mass: 1, price: 1e102},
    e103: {name: "$10 Tretrigintillion Bill", group: "Money", mass: 1, price: 1e103},
    e104: {name: "$100 Tretrigintillion Bill", group: "Money", mass: 1, price: 1e104},
    e105: {name: "$1 Quattuortrigintillion Bill", group: "Money", mass: 1, price: 1e105},
    e106: {name: "$10 Quattuortrigintillion Bill", group: "Money", mass: 1, price: 1e106},
    e107: {name: "$100 Quattuortrigintillion Bill", group: "Money", mass: 1, price: 1e107},
    e108: {name: "$1 Quintrigintillion Bill", group: "Money", mass: 1, price: 1e108},
    e109: {name: "$10 Quintrigintillion Bill", group: "Money", mass: 1, price: 1e109},
    e110: {name: "$100 Quintrigintillion Bill", group: "Money", mass: 1, price: 1e110},
    e111: {name: "$1 Sextrigintillion Bill", group: "Money", mass: 1, price: 1e111},
    e112: {name: "$10 Sextrigintillion Bill", group: "Money", mass: 1, price: 1e112},
    e113: {name: "$100 Sextrigintillion Bill", group: "Money", mass: 1, price: 1e113},
    e114: {name: "$1 Septentrigintillion Bill", group: "Money", mass: 1, price: 1e114},
    e115: {name: "$10 Septentrigintillion Bill", group: "Money", mass: 1, price: 1e115},
    e116: {name: "$100 Septentrigintillion Bill", group: "Money", mass: 1, price: 1e116},
    e117: {name: "$1 Octotrigintillion Bill", group: "Money", mass: 1, price: 1e117},
    e118: {name: "$10 Octotrigintillion Bill", group: "Money", mass: 1, price: 1e118},
    e119: {name: "$100 Octotrigintillion Bill", group: "Money", mass: 1, price: 1e119},
    e120: {name: "$1 Novemtrigintillion Bill", group: "Money", mass: 1, price: 1e120},
    e121: {name: "$10 Novemtrigintillion Bill", group: "Money", mass: 1, price: 1e121},
    e122: {name: "$100 Novemtrigintillion Bill", group: "Money", mass: 1, price: 1e122},
    e123: {name: "$1 Quadragintillion Bill", group: "Money", mass: 1, price: 1e123},
    e124: {name: "$10 Quadragintillion Bill", group: "Money", mass: 1, price: 1e124},
    e125: {name: "$100 Quadragintillion Bill", group: "Money", mass: 1, price: 1e125},
    e126: {name: "$1 Unquadragintillion Bill", group: "Money", mass: 1, price: 1e126},
    e127: {name: "$10 Unquadragintillion Bill", group: "Money", mass: 1, price: 1e127},
    e128: {name: "$100 Unquadragintillion Bill", group: "Money", mass: 1, price: 1e128},
    e129: {name: "$1 Duoquadragintillion Bill", group: "Money", mass: 1, price: 1e129},
    e130: {name: "$10 Duoquadragintillion Bill", group: "Money", mass: 1, price: 1e130},
    e131: {name: "$100 Duoquadragintillion Bill", group: "Money", mass: 1, price: 1e131},
    e132: {name: "$1 Trequadragintillion Bill", group: "Money", mass: 1, price: 1e132},
    e133: {name: "$10 Trequadragintillion Bill", group: "Money", mass: 1, price: 1e133},
    e134: {name: "$100 Trequadragintillion Bill", group: "Money", mass: 1, price: 1e134},
    e135: {name: "$1 Quattuorquadragintillion Bill", group: "Money", mass: 1, price: 1e135},
    e136: {name: "$10 Quattuorquadragintillion Bill", group: "Money", mass: 1, price: 1e136},
    e137: {name: "$100 Quattuorquadragintillion Bill", group: "Money", mass: 1, price: 1e137},
    e138: {name: "$1 Quinquadragintillion Bill", group: "Money", mass: 1, price: 1e138},
    e139: {name: "$10 Quinquadragintillion Bill", group: "Money", mass: 1, price: 1e139},
    e140: {name: "$100 Quinquadragintillion Bill", group: "Money", mass: 1, price: 1e140},
    e141: {name: "$1 Sexquadragintillion Bill", group: "Money", mass: 1, price: 1e141},
    e142: {name: "$10 Sexquadragintillion Bill", group: "Money", mass: 1, price: 1e142},
    e143: {name: "$100 Sexquadragintillion Bill", group: "Money", mass: 1, price: 1e143},
    e144: {name: "$1 Septenquadragintillion Bill", group: "Money", mass: 1, price: 1e144},
    e145: {name: "$10 Septenquadragintillion Bill", group: "Money", mass: 1, price: 1e145},
    e146: {name: "$100 Septenquadragintillion Bill", group: "Money", mass: 1, price: 1e146},
    e147: {name: "$1 Octoquadragintillion Bill", group: "Money", mass: 1, price: 1e147},
    e148: {name: "$10 Octoquadragintillion Bill", group: "Money", mass: 1, price: 1e148},
    e149: {name: "$100 Octoquadragintillion Bill", group: "Money", mass: 1, price: 1e149},
    e150: {name: "$1 Novemquadragintillion Bill", group: "Money", mass: 1, price: 1e150},
    e151: {name: "$10 Novemquadragintillion Bill", group: "Money", mass: 1, price: 1e151},
    e152: {name: "$100 Novemquadragintillion Bill", group: "Money", mass: 1, price: 1e152},
    e153: {name: "$1 Quinquagintillion Bill", group: "Money", mass: 1, price: 1e153}
};

const animations = {
    autoCutter: {
        img: [
            "img/autoCutter/0.png",
            "img/autoCutter/1.png",
            "img/autoCutter/2.png",
            "img/autoCutter/3.png",
            "img/autoCutter/4.png",
            "img/autoCutter/5.png",
            "img/autoCutter/6.png",
            "img/autoCutter/7.png"
        ],
        fps: 50
    }
};